# Generated by Django 5.1.4 on 2024-12-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0003_customuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Manager', 'Manager'), ('Staff', 'Staff')], max_length=50),
        ),
    ]
