# Generated by Django 5.1.4 on 2024-12-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(editable=False, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=50)),
                ('product_quantity', models.FloatField(default=0)),
                ('transaction_type', models.CharField(choices=[('sell', 'Sell'), ('buy', 'Buy')], default='buy', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.FloatField(default=0)),
                ('transaction_type', models.CharField(choices=[('sell', 'Sell'), ('buy', 'Buy')], max_length=10)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapi.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.FloatField(default=0)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('sell', 'Sell'), ('buy', 'Buy')], max_length=10)),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productapi.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapi.units'),
        ),
    ]
