# Generated by Django 5.1.4 on 2024-12-17 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0004_alter_customuser_role'),
        ('productapi', '0002_product_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='authapi.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productstock',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='authapi.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='units',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='authapi.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='authapi.company'),
        ),
    ]
