# Generated by Django 5.1.4 on 2024-12-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0005_rename_product_id_history_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='product',
            new_name='product_id',
        ),
    ]
