# Generated by Django 5.1.4 on 2024-12-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0006_rename_product_history_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='product_id',
            new_name='product',
        ),
    ]
