# Generated by Django 5.1.4 on 2024-12-17 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0007_rename_product_id_history_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='productapi.product'),
        ),
    ]
